[pytest]
markers =
    pet: Testes do endpoint Pet
    store: Testes do endpoint Store
    user: Testes do endpoint User
    smoke: Testes de smoke (rápidos)
    regression: Testes de regressão
    login: Testes de login
    cart: Testes de carrinho
    checkout: Testes de checkout
    e2e: Fluxo ponta a ponta
