[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts =
    -v
    --tb=short
    --strict-markers
    --html=reports/report.html
    --self-contained-html
markers =
    pet: Testes do endpoint Pet
    store: Testes do endpoint Store
    user: Testes do endpoint User
    smoke: Testes de smoke (rápidos)
    regression: Testes de regressão
