[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts =
    -v
    --tb=short
    --strict-markers
    --html=reports/report.html
    --self-contained-html
markers =
    login: Testes de login
    cart: Testes de carrinho
    checkout: Testes de checkout
    e2e: Fluxo ponta a ponta
    smoke: Testes de smoke
